// 実OneSDKと外部通信を遮断し、公開ページの操作を確認する。
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const parent = path.resolve(__dirname,'../..');
const server = http.createServer((req,res) => {
  const file = path.resolve(parent,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));
  if(!file.startsWith(parent+path.sep) || !fs.existsSync(file) || !fs.statSync(file).isFile()) { res.writeHead(404);res.end();return; }
  if(file.endsWith('onesdk.js')) { res.end('');return; }
  res.setHeader('Content-Type', ({'.js':'text/javascript','.css':'text/css','.html':'text/html'})[path.extname(file)] || 'text/plain');
  res.end(fs.readFileSync(file));
});
(async () => {
  let browser;
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  try {
    browser=await chromium.launch({channel:'chrome',headless:true});
    const context=await browser.newContext({viewport:{width:1280,height:720}});
    const origin=`http://127.0.0.1:${server.address().port}`;
    await context.route('**/*',route=>route.request().url().startsWith(origin)?route.continue():route.abort());
    await context.addInitScript(()=>{ window.OneSDK={setup(){},subscribe(){},ready:()=>Promise.resolve(),connect(){}}; });
    const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(origin+'/custom_base_template_V3_dev/index.html');
    await page.waitForFunction(()=>window.VCT_SETTINGS_LAUNCHER || document.getElementById('vct-settings-launcher'));
    await page.locator('#vct-settings-launcher').click();
    const widthInput = page.locator('[data-config-key="COMMENT_WIDTH"]');
    await widthInput.fill('');
    await widthInput.pressSequentially('321');
    assert.equal(await widthInput.inputValue(), '321');
    assert.equal(await page.locator('#app').evaluate(el => el.style.width), '760px');
    await widthInput.press('Enter');
    assert.equal(await page.locator('#app').evaluate(el => el.style.width), '321px');
    await widthInput.fill('2');
    assert.equal(await widthInput.inputValue(), '2');
    await widthInput.press('Tab');
    assert.equal(await widthInput.inputValue(), '160');
    await widthInput.fill('');
    await widthInput.press('Enter');
    assert.equal(await widthInput.inputValue(), '160');
    await page.locator('[data-placement-slider="COMMENT_WIDTH"]').fill('500');
    assert.equal(await widthInput.inputValue(), '500');
    await widthInput.fill('503');
    await widthInput.press('Enter');
    assert.equal(await page.locator('#app').evaluate(el => el.style.width), '503px');
    const scaleInput = page.locator('[data-config-key="COMMENT_SCALE"]');
    await scaleInput.fill('');
    await scaleInput.pressSequentially('0.37');
    assert.equal(await scaleInput.inputValue(), '0.37');
    await scaleInput.press('Enter');
    assert.equal(await page.locator('#app').evaluate(el => el.style.transform), 'scale(0.37)');
    await page.evaluate(()=>window.VCT_SETTINGS_PANEL.close());
    await page.locator('#vct-settings-launcher').click();
    await page.getByRole('button',{name:'通常を試す',exact:true}).click();
    await page.getByRole('button',{name:'支援を試す',exact:true}).click();
    await page.getByRole('button',{name:'メンバーを試す',exact:true}).click();
    assert.equal(await page.locator('.cmt').count(),3);
    assert.equal(await page.locator('.effect-root').count(),2);
    assert.match(await page.locator('.cmt__message').first().innerText(),/表示確認/);
    await page.locator('[data-config-key="FX_GLOW_SIZE"]').fill('24');
    assert.match(await page.locator('.effect-root > div').first().getAttribute('style'),/24px/);
    await page.locator('[data-config-key="EFFECT_ENABLED"]').uncheck();
    assert.equal(await page.locator('.effect-root').count(),0);
    await page.evaluate(()=>window.VCT_SETTINGS_PANEL.close());
    await page.waitForFunction(()=>document.querySelectorAll('.effect-root').length===2);
    await page.locator('#vct-settings-launcher').click();
    await page.getByRole('button',{name:'マウス配置の開始／終了'}).click();
    const rect=await page.locator('#placement-editor').boundingBox();
    await page.mouse.move(rect.x+20,rect.y+20);await page.mouse.down();await page.mouse.move(rect.x+80,rect.y+50);await page.mouse.up();
    assert.equal(await page.locator('[data-config-key="COMMENT_X"]').inputValue(),'170');
    await page.mouse.wheel(0,-100);
    await page.waitForFunction(()=>document.querySelector('[data-config-key="COMMENT_SCALE"]').value==='1.05');
    await page.getByRole('button',{name:'保存して再読み込み'}).click();
    await page.waitForFunction(()=>window.CONFIG?.COMMENT_X===170);
    await page.locator('#vct-settings-launcher').click();
    await page.getByRole('button',{name:'支援を試す',exact:true}).click();
    await page.getByRole('button',{name:'コメント消去',exact:true}).click();
    await page.waitForFunction(()=>document.querySelectorAll('.effect-root').length===0);
    await page.getByRole('button',{name:'支援を試す',exact:true}).click();
    await page.evaluate(()=>window.VCT_SETTINGS_PANEL.close());
    await page.waitForFunction(()=> { const el=document.querySelector('.cmt'); return el && el.getBoundingClientRect().height>10 && getComputedStyle(el.closest('.cmt-shell')).opacity==='1'; });
    // 縦横比の異なる画像を生成し、外部通信なしで素材切替を確認する。
    const png = await page.evaluate(() => { const c=document.createElement('canvas');c.width=80;c.height=40;const ctx=c.getContext('2d');ctx.fillStyle='#23aacc';ctx.fillRect(0,0,80,40);return c.toDataURL().split(',')[1]; });
    await context.route('**/assets/test%20image.png', route=>route.fulfill({contentType:'image/png',body:Buffer.from(png,'base64')}));
    await page.locator('#vct-settings-launcher').click();
    const mode=page.locator('[data-config-key="FX_MATERIAL_MODE"]');
    const filename=page.locator('[data-config-key="FX_MATERIAL_FILE"]');
    assert.equal(await mode.inputValue(),'emoji');
    assert.equal(await filename.isVisible(),false);
    let releaseImage;
    const imageGate = new Promise(resolve=>{ releaseImage=resolve; });
    let pendingImages=0;
    await context.route('**/assets/slow.png', async route=>{ pendingImages++; await imageGate; await route.fulfill({contentType:'image/png',body:Buffer.from(png,'base64')}); });
    await mode.selectOption('image');
    const slowRequest=page.waitForRequest('**/assets/slow.png');
    await filename.fill('slow.png');
    await slowRequest;
    await mode.selectOption('emoji');
    releaseImage();
    await page.waitForLoadState('networkidle');
    assert.ok(pendingImages>0);
    assert.equal(await page.locator('.effect-root .vct-material img').count(),0);
    await mode.selectOption('image');
    await filename.fill('missing.png');
    await page.waitForFunction(()=>document.querySelector('.vct-material-preview [role="status"]').textContent.includes('読み込めません'));
    assert.equal(await page.locator('.effect-root .vct-material').innerText(),'✨');
    await filename.fill('../outside.png');
    await page.waitForFunction(()=>document.querySelector('.vct-material-preview [role="status"]').textContent.includes('ファイル名を確認'));
    await filename.fill('test image.png');
    await page.waitForFunction(()=>document.querySelector('.effect-root .vct-material img')?.naturalWidth===80);
    const size=page.locator('[data-config-key="FX_MATERIAL_SIZE"]');
    await size.fill('48');await size.press('Enter');
    assert.equal(await page.locator('.effect-root .vct-material').evaluate(el=>el.style.width),'48px');
    assert.equal(await page.locator('.effect-root .vct-material img').evaluate(el=>getComputedStyle(el).objectFit),'contain');
    await page.evaluate(()=>window.VCT_SETTINGS_PANEL.close());
    await page.waitForFunction(()=>!document.querySelector('.effect-root .vct-material img'));
    await page.locator('#vct-settings-launcher').click();
    await mode.selectOption('image');await filename.fill('test image.png');
    await size.fill('48');await size.press('Enter');
    await page.getByRole('button',{name:'保存して再読み込み'}).click();
    await page.waitForFunction(()=>window.CONFIG?.FX_MATERIAL_MODE==='image');
    assert.equal(await page.evaluate(()=>window.CONFIG.FX_MATERIAL_FILE),'test image.png');
    assert.equal(await page.evaluate(()=>window.CONFIG.FX_MATERIAL_SIZE),48);
    await page.locator('#vct-settings-launcher').click();
    await page.getByRole('button',{name:'支援を試す',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('.effect-root .vct-material img')?.naturalWidth===80);
    await mode.selectOption('emoji');
    await page.waitForFunction(()=>!document.querySelector('.effect-root .vct-material img'));
    await page.evaluate(()=>window.VCT_SETTINGS_PANEL.close());
    await page.waitForFunction(()=>document.querySelector('.effect-root .vct-material img')?.naturalWidth===80);
    await page.waitForFunction(()=>{ const el=document.querySelector('.cmt-shell');return el && getComputedStyle(el).opacity==='1' && !el.classList.contains('list-enter-active'); });
    await page.screenshot({path:path.join(__dirname,'preview.png')});
    // 本体を変えず、選択先の演出だけを別実装として検証する。
    await context.route('**/effects/glow.js', route=>route.fulfill({contentType:'text/javascript',body:`window.VCT_EFFECT={apiVersion:1,id:'probe',title:'差替え確認',defaults:{FX_PROBE_SIZE:7},fields:{FX_PROBE_SIZE:{type:'number',label:'試験サイズ'}},mount({root,settings}){root.dataset.probe=settings.FX_PROBE_SIZE;return {update(next){root.dataset.probe=next.FX_PROBE_SIZE;},destroy(){root.remove();}};}};`}));
    await page.reload();
    await page.locator('#vct-settings-launcher').click();
    await page.getByRole('button',{name:'支援を試す',exact:true}).click();
    assert.equal(await page.locator('.effect-root').getAttribute('data-probe'),'7');
    assert.equal(await page.locator('[data-config-key="FX_MATERIAL_MODE"]').count(),0);
    await page.locator('[data-config-key="FX_PROBE_SIZE"]').fill('9');
    assert.equal(await page.locator('.effect-root').getAttribute('data-probe'),'9');
    await page.getByRole('button',{name:'コメント消去',exact:true}).click();
    await page.waitForFunction(()=>document.querySelectorAll('.effect-root').length===0);
    const local=await browser.newContext();
    await local.route('**/*',route=>route.request().url().endsWith('/onesdk.js')?route.fulfill({body:''}):route.request().url().startsWith('file:')?route.continue():route.abort());
    await local.route('**/assets/test%20image.png',route=>route.fulfill({contentType:'image/png',body:Buffer.from(png,'base64')}));
    await local.addInitScript(()=>{window.OneSDK={setup(){},subscribe(){},ready:()=>Promise.resolve(),connect(){}};});
    const filePage=await local.newPage();filePage.on('pageerror',e=>errors.push(e.message));
    await filePage.goto(require('node:url').pathToFileURL(path.join(parent,'custom_base_template_V3_dev/index.html')).href);
    await filePage.locator('#vct-settings-launcher').click();
    await filePage.getByRole('button',{name:'支援を試す',exact:true}).click();
    assert.equal(await filePage.locator('.effect-root').count(),1);
    await filePage.locator('[data-config-key="FX_MATERIAL_MODE"]').selectOption('image');
    await filePage.locator('[data-config-key="FX_MATERIAL_FILE"]').fill('test image.png');
    await filePage.waitForFunction(()=>document.querySelector('.effect-root .vct-material img')?.naturalWidth===80);
    await local.close();
    assert.deepEqual(errors,[]);
    console.log('PASS: 表示・配置・演出・素材切替・読込競合・画像失敗・サイズ・保存取消・モジュール差替え・file起動');
  } finally { await browser?.close();await new Promise(resolve=>server.close(resolve)); }
})().catch(error=>{console.error(error);process.exitCode=1;});
