const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const window = {};
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../widgets/comments/display/main.js'), 'utf8'), { window, getComputedStyle: el => ({ width: el.getBoundingClientRect().width }) });
const display = window.VCT_DISPLAY;
test('中心座標・ばらつき・倍率は独立し、再計算しても配置を保持する', () => {
  const comment = { popupSeed: { x: 0, y: 1 }, displayOrder: 4 };
  const c = { DISPLAY_MODE: 'popup' };
  assert.equal(display.style(comment, c).left, '0%');
  assert.equal(display.style(comment, c).top, '100%');
  const anchor = { ...c, POPUP_PLACEMENT: 'anchor', POPUP_X: 50, POPUP_Y: 40, POPUP_SPREAD_X: 8, POPUP_SPREAD_Y: 6 };
  assert.equal(display.style(comment, anchor).left, '42%');
  assert.equal(display.style(comment, anchor).top, '46%');
  assert.equal(display.style(comment, { ...anchor, POPUP_SCALE: 50 }).left, '42%');
  assert.equal(display.style(comment, { ...anchor, POPUP_SCALE: 50 }).width, '420px');
  assert.equal(display.style(comment, { ...anchor, POPUP_SCALE: 50 })['--popup-scale'], .5);
  assert.equal(Object.keys(display.style(comment, { DISPLAY_MODE: 'stack' })).length, 0);
});
test('clear・上限除去・同一ID再受信のタイマー独立性と方式変更', () => {
  let now = 1000, next = 0;
  const jobs = new Map(), removed = [];
  const clock = { now: () => now, setTimeout: (fn, delay) => { jobs.set(++next, { fn, at: now + delay }); return next; }, clearTimeout: id => jobs.delete(id) };
  const life = display.createLifetime(key => removed.push(key), clock);
  const a = { id: 'same', displayOrder: 1, displayStartedAt: now };
  const b = { id: 'same', displayOrder: 2, displayStartedAt: now + 500 };
  life.sync([a], { DISPLAY_MODE: 'popup', POPUP_DURATION: 2 });
  assert.equal(jobs.size, 1);
  life.sync([b], { DISPLAY_MODE: 'popup', POPUP_DURATION: 2 });
  assert.equal(jobs.size, 1);
  [...jobs.values()][0].fn(); assert.deepEqual(removed, [2]); jobs.clear();
  life.sync([a], { DISPLAY_MODE: 'popup', POPUP_DURATION: 2 });
  life.sync([a], { DISPLAY_MODE: 'stack', AUTO_HIDE_MS: 0 }); assert.equal(jobs.size, 0);
  life.sync([a], { DISPLAY_MODE: 'popup', POPUP_DURATION: 2 });
  life.clear(); assert.equal(jobs.size, 0);
  assert.equal(display.capacity({ DISPLAY_MODE: 'popup', POPUP_MAX_ITEMS: 3 }), 3);
});
